version: 0.2

env:
  secrets-manager:
    VAPOR_API_TOKEN: gpug/staging:VAPOR_API_TOKEN

phases:
  install:
    runtime-versions:
      php: 7.3
    commands:
      - apt-get update
      - apt-get install -y libzip-dev
      - pecl install zip
      - echo 'extension=zip.so' > /usr/local/etc/php/conf.d/zip.ini
  pre_build:
    commands:
      - composer install
      - cp .env.example .env.testing
      - php artisan key:generate --env=testing
  build:
    commands:
      - vendor/bin/phpunit
  post_build:
    commands:
      - vendor/bin/vapor deploy staging
